import { Profile } from '@/types/profile';

export function fetchProfiles(
  page: number = 1,
  pageSize: number = 10
): Promise<{ profiles: Profile[]; total: number; nextPage: number | null }> {
  const mockProfiles: Profile[] = [
    {
      firstName: 'Alice',
      lastName: 'Smith',
      age: 25,
      images: [
        'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
        'https://images.unsplash.com/photo-1519125323398-675f0ddb6308',
      ],
      bio: 'Adventure seeker and coffee enthusiast. Love hiking, reading, and trying new cuisines.',
      interests: [
        'Hiking',
        'Photography',
        'Coffee',
        'Travel',
        'Books',
        'Yoga',
        'Music',
        'Art',
        'Cooking',
        'Fitness',
      ],
      occupation: 'Marketing Manager',
      location: 'San Francisco, CA',
      distance: '2 miles away',
    },
    {
      firstName: 'Bob',
      lastName: 'Johnson',
      age: 28,
      images: [
        'https://images.unsplash.com/photo-1511367461989-f85a21fda167',
        'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
      ],
      bio: 'Software engineer by day, musician by night. Always looking for the next great adventure.',
      interests: [
        'Music',
        'Programming',
        'Gaming',
        'Movies',
        'Guitar',
        'Rock Climbing',
        'Beer',
        'Tech',
        'Basketball',
        'Travel',
      ],
      occupation: 'Software Engineer',
      location: 'Austin, TX',
      distance: '5 miles away',
    },
    {
      firstName: 'Charlie',
      lastName: 'Brown',
      age: 22,
      images: [
        'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
        'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
      ],
      bio: 'College student studying psychology. Love meeting new people and exploring the city.',
      interests: [
        'Psychology',
        'Dancing',
        'Movies',
        'Friends',
        'Parties',
        'Netflix',
        'Food',
        'Shopping',
        'Concerts',
        'Social Media',
      ],
      occupation: 'Student',
      location: 'Los Angeles, CA',
      distance: '1 mile away',
    },
    {
      firstName: 'Diana',
      lastName: 'Prince',
      age: 27,
      images: [
        'https://images.unsplash.com/photo-1517841905240-472988babdf9',
        'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91',
      ],
      bio: 'Lawyer with a passion for justice and equality. Enjoy wine tasting and weekend getaways.',
      interests: [
        'Law',
        'Wine',
        'Politics',
        'Travel',
        'Reading',
        'Running',
        'Volunteering',
        'Documentaries',
        'Debates',
        'History',
      ],
      occupation: 'Lawyer',
      location: 'New York, NY',
      distance: '3 miles away',
    },
    {
      firstName: 'Ethan',
      lastName: 'Hunt',
      age: 30,
      images: [
        'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
        'https://images.unsplash.com/photo-1465101178521-c1a4c8a0f8f5',
      ],
      bio: 'Action movie enthusiast and fitness trainer. Looking for someone who can keep up with my active lifestyle.',
      interests: [
        'Fitness',
        'Movies',
        'Martial Arts',
        'Running',
        'Cycling',
        'Swimming',
        'Nutrition',
        'Travel',
        'Adventure Sports',
        'Boxing',
      ],
      occupation: 'Fitness Trainer',
      location: 'Miami, FL',
      distance: '7 miles away',
    },
    {
      firstName: 'Fiona',
      lastName: 'Gallagher',
      age: 24,
      images: [
        'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91',
        'https://images.unsplash.com/photo-1519985176271-adb1088fa94c',
      ],
      bio: 'Artist and free spirit. Love painting, music festivals, and spontaneous road trips.',
      interests: [
        'Art',
        'Painting',
        'Music Festivals',
        'Indie Music',
        'Vintage Fashion',
        'Photography',
        'Poetry',
        'Coffee Shops',
        'Thrift Shopping',
        'Nature',
      ],
      occupation: 'Artist',
      location: 'Portland, OR',
      distance: '4 miles away',
    },
    {
      firstName: 'George',
      lastName: 'Miller',
      age: 29,
      images: [
        'https://images.unsplash.com/photo-1519340333755-c6e2a6c7b8a0',
        'https://images.unsplash.com/photo-1524253482453-3fed8d2fe12b',
      ],
      bio: 'Chef who loves experimenting with fusion cuisine. Foodie looking for someone to share culinary adventures.',
      interests: [
        'Cooking',
        'Food',
        'Restaurants',
        'Wine',
        'Travel',
        'Culture',
        'Markets',
        'Spices',
        'Baking',
        'Gastronomy',
      ],
      occupation: 'Chef',
      location: 'Chicago, IL',
      distance: '6 miles away',
    },
    {
      firstName: 'Hannah',
      lastName: 'Williams',
      age: 26,
      images: [
        'https://images.unsplash.com/photo-1519125323398-675f0ddb6308',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
      ],
      bio: 'Nurse with a big heart. Love helping others and spending time with family and friends.',
      interests: [
        'Healthcare',
        'Volunteering',
        'Family',
        'Friends',
        'Movies',
        'Books',
        'Gardening',
        'Baking',
        'Animals',
        'Community Service',
      ],
      occupation: 'Nurse',
      location: 'Denver, CO',
      distance: '2 miles away',
    },
    {
      firstName: 'Ian',
      lastName: 'Curtis',
      age: 31,
      images: [
        'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
        'https://images.unsplash.com/photo-1511367461989-f85a21fda167',
      ],
      bio: 'Musician and songwriter. Looking for someone who appreciates good music and deep conversations.',
      interests: [
        'Music',
        'Songwriting',
        'Guitar',
        'Vinyl Records',
        'Concerts',
        'Poetry',
        'Philosophy',
        'Literature',
        'Coffee',
        'Indie Films',
      ],
      occupation: 'Musician',
      location: 'Nashville, TN',
      distance: '8 miles away',
    },
    {
      firstName: 'Julia',
      lastName: 'Roberts',
      age: 32,
      images: [
        'https://images.unsplash.com/photo-1465101178521-c1a4c8a0f8f5',
        'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
      ],
      bio: 'Doctor dedicated to helping others. Love traveling, fine dining, and cultural experiences.',
      interests: [
        'Medicine',
        'Travel',
        'Fine Dining',
        'Culture',
        'Theater',
        'Opera',
        'Art Galleries',
        'Languages',
        'Charity Work',
        'Wellness',
      ],
      occupation: 'Doctor',
      location: 'Boston, MA',
      distance: '3 miles away',
    },
    {
      firstName: 'Karen',
      lastName: 'Lee',
      age: 23,
      images: [
        'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
        'https://images.unsplash.com/photo-1519985176271-adb1088fa94c',
      ],
      bio: 'Fashion design student with a passion for sustainable fashion and social justice.',
      interests: [
        'Fashion',
        'Design',
        'Sustainability',
        'Social Justice',
        'Sewing',
        'Thrifting',
        'Photography',
        'Modeling',
        'Art',
        'Environment',
      ],
      occupation: 'Fashion Design Student',
      location: 'Seattle, WA',
      distance: '1 mile away',
    },
    {
      firstName: 'Liam',
      lastName: 'Nguyen',
      age: 27,
      images: [
        'https://images.unsplash.com/photo-1508672019048-805c876b67e2',
        'https://images.unsplash.com/photo-1524253482453-3fed8d2fe12b',
      ],
      bio: 'Data scientist who loves solving complex problems. Enjoy hiking, board games, and craft beer.',
      interests: [
        'Data Science',
        'Technology',
        'Hiking',
        'Board Games',
        'Craft Beer',
        'Puzzles',
        'Mathematics',
        'Camping',
        'Science',
        'Coding',
      ],
      occupation: 'Data Scientist',
      location: 'San Jose, CA',
      distance: '9 miles away',
    },
    {
      firstName: 'Mia',
      lastName: 'Martinez',
      age: 28,
      images: [
        'https://images.unsplash.com/photo-1519985176271-adb1088fa94c',
        'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      ],
      bio: 'Teacher who loves inspiring young minds. Passionate about education and making a difference.',
      interests: [
        'Education',
        'Teaching',
        'Children',
        'Books',
        'Learning',
        'Community',
        'Volunteering',
        'Travel',
        'Languages',
        'Culture',
      ],
      occupation: 'Teacher',
      location: 'Phoenix, AZ',
      distance: '4 miles away',
    },
    {
      firstName: 'Noah',
      lastName: 'Kim',
      age: 26,
      images: [
        'https://images.unsplash.com/photo-1524253482453-3fed8d2fe12b',
        'https://images.unsplash.com/photo-1517841905240-472988babdf9',
      ],
      bio: 'Architect who designs sustainable buildings. Love modern art, urban exploration, and minimalism.',
      interests: [
        'Architecture',
        'Design',
        'Sustainability',
        'Modern Art',
        'Urban Exploration',
        'Minimalism',
        'Photography',
        'Cities',
        'Innovation',
        'Environment',
      ],
      occupation: 'Architect',
      location: 'Portland, OR',
      distance: '5 miles away',
    },
    {
      firstName: 'Olivia',
      lastName: 'Garcia',
      age: 25,
      images: [
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        'https://images.unsplash.com/photo-1519125323398-675f0ddb6308',
      ],
      bio: 'Veterinarian who adores animals. Looking for someone who shares my love for pets and nature.',
      interests: [
        'Animals',
        'Veterinary Medicine',
        'Nature',
        'Hiking',
        'Pets',
        'Wildlife',
        'Conservation',
        'Outdoors',
        'Photography',
        'Animal Rescue',
      ],
      occupation: 'Veterinarian',
      location: 'Sacramento, CA',
      distance: '6 miles away',
    },
    {
      firstName: 'Paul',
      lastName: 'Walker',
      age: 31,
      images: [
        'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
        'https://images.unsplash.com/photo-1508672019048-805c876b67e2',
      ],
      bio: 'Car enthusiast and mechanic. Love racing, road trips, and anything with an engine.',
      interests: [
        'Cars',
        'Racing',
        'Mechanics',
        'Road Trips',
        'Motorcycles',
        'Speed',
        'Auto Shows',
        'Engineering',
        'Adventure',
        'Travel',
      ],
      occupation: 'Automotive Engineer',
      location: 'Detroit, MI',
      distance: '7 miles away',
    },
    {
      firstName: 'Quinn',
      lastName: 'Evans',
      age: 29,
      images: [
        'https://images.unsplash.com/photo-1519125323398-675f0ddb6308',
        'https://images.unsplash.com/photo-1519985176271-adb1088fa94c',
      ],
      bio: 'Freelance writer and blogger. Love storytelling, travel writing, and discovering hidden gems.',
      interests: [
        'Writing',
        'Blogging',
        'Storytelling',
        'Travel',
        'Literature',
        'Journalism',
        'Books',
        'Coffee Shops',
        'Culture',
        'Languages',
      ],
      occupation: 'Freelance Writer',
      location: 'Minneapolis, MN',
      distance: '3 miles away',
    },
    {
      firstName: 'Rachel',
      lastName: 'Adams',
      age: 28,
      images: [
        'https://images.unsplash.com/photo-1511367461989-f85a21fda167',
        'https://images.unsplash.com/photo-1465101178521-c1a4c8a0f8f5',
      ],
      bio: 'Physical therapist helping people recover and get stronger. Love fitness, wellness, and outdoor activities.',
      interests: [
        'Physical Therapy',
        'Fitness',
        'Wellness',
        'Running',
        'Yoga',
        'Swimming',
        'Health',
        'Nutrition',
        'Outdoors',
        'Sports',
      ],
      occupation: 'Physical Therapist',
      location: 'Tampa, FL',
      distance: '4 miles away',
    },
    {
      firstName: 'Sam',
      lastName: 'Taylor',
      age: 27,
      images: [
        'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
        'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
      ],
      bio: 'Graphic designer with a passion for creativity. Love visual arts, design trends, and innovative projects.',
      interests: [
        'Graphic Design',
        'Visual Arts',
        'Creativity',
        'Digital Art',
        'Branding',
        'Typography',
        'Photography',
        'Innovation',
        'Technology',
        'Freelancing',
      ],
      occupation: 'Graphic Designer',
      location: 'Atlanta, GA',
      distance: '2 miles away',
    },
    {
      firstName: 'Tina',
      lastName: 'Chen',
      age: 24,
      images: [
        'https://images.unsplash.com/photo-1517841905240-472988babdf9',
        'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91',
      ],
      bio: 'Psychology graduate student researching human behavior. Love deep conversations and understanding people.',
      interests: [
        'Psychology',
        'Research',
        'Human Behavior',
        'Books',
        'Philosophy',
        'Mental Health',
        'Science',
        'Academia',
        'Learning',
        'Therapy',
      ],
      occupation: 'Graduate Student',
      location: 'Madison, WI',
      distance: '5 miles away',
    },
    {
      firstName: 'Victor',
      lastName: 'Harris',
      age: 32,
      images: [
        'https://images.unsplash.com/photo-1465101178521-c1a4c8a0f8f5',
        'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      ],
      bio: 'Investment banker with a love for numbers and strategy. Enjoy fine wine, golf, and luxury travel.',
      interests: [
        'Finance',
        'Investment',
        'Golf',
        'Wine',
        'Luxury Travel',
        'Business',
        'Strategy',
        'Economics',
        'Networking',
        'Fine Dining',
      ],
      occupation: 'Investment Banker',
      location: 'New York, NY',
      distance: '8 miles away',
    },
    {
      firstName: 'Wendy',
      lastName: 'Moore',
      age: 30,
      images: [
        'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91',
        'https://images.unsplash.com/photo-1519985176271-adb1088fa94c',
      ],
      bio: 'Social worker dedicated to helping families and communities. Love volunteering and making a positive impact.',
      interests: [
        'Social Work',
        'Community Service',
        'Volunteering',
        'Family',
        'Children',
        'Advocacy',
        'Non-profit',
        'Social Justice',
        'Counseling',
        'Helping Others',
      ],
      occupation: 'Social Worker',
      location: 'Philadelphia, PA',
      distance: '3 miles away',
    },
    {
      firstName: 'Xander',
      lastName: 'Scott',
      age: 29,
      images: [
        'https://images.unsplash.com/photo-1519340333755-c6e2a6c7b8a0',
        'https://images.unsplash.com/photo-1524253482453-3fed8d2fe12b',
      ],
      bio: 'Video game developer creating immersive experiences. Love gaming, technology, and virtual reality.',
      interests: [
        'Game Development',
        'Gaming',
        'Technology',
        'Virtual Reality',
        'Programming',
        'Animation',
        'Esports',
        'Computers',
        'Innovation',
        'Creativity',
      ],
      occupation: 'Game Developer',
      location: 'San Francisco, CA',
      distance: '6 miles away',
    },
    {
      firstName: 'Yara',
      lastName: 'Patel',
      age: 26,
      images: [
        'https://images.unsplash.com/photo-1519125323398-675f0ddb6308',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
      ],
      bio: 'Environmental scientist working to protect our planet. Passionate about sustainability and climate action.',
      interests: [
        'Environmental Science',
        'Sustainability',
        'Climate Change',
        'Conservation',
        'Nature',
        'Research',
        'Activism',
        'Green Energy',
        'Ecology',
        'Planet Earth',
      ],
      occupation: 'Environmental Scientist',
      location: 'Boulder, CO',
      distance: '4 miles away',
    },
    {
      firstName: 'Zane',
      lastName: 'King',
      age: 31,
      images: [
        'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
        'https://images.unsplash.com/photo-1511367461989-f85a21fda167',
      ],
      bio: 'Pilot who loves exploring the world from above. Adventure seeker looking for a co-pilot in life.',
      interests: [
        'Aviation',
        'Flying',
        'Travel',
        'Adventure',
        'Geography',
        'Weather',
        'Navigation',
        'Airplanes',
        'Exploration',
        'Freedom',
      ],
      occupation: 'Commercial Pilot',
      location: 'Dallas, TX',
      distance: '7 miles away',
    },
  ];

  const total = mockProfiles.length;
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  const paginatedProfiles = mockProfiles.slice(start, end);

  const nextPage = end < total ? page + 1 : null;

  return new Promise<{ profiles: Profile[]; total: number; nextPage: number | null }>((resolve) => {
    setTimeout(() => resolve({ profiles: paginatedProfiles, total, nextPage }), 300);
  });
}
